name: outline_gradient_button
description: OutlineGradientButton package developed to create buttons with gradient outline.
version: 1.0.0+2
homepage: https://github.com/kalaganov/outline_gradient_button

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
